#include <cstdint>

#include <rex/ppc.h>

using RexPPCFunc = void (*)(PPCContext& ctx, std::uint8_t* base);

extern "C" void daytona_call_import(
    const char* imp_name,
    const char* plain_name,
    const char* underscored_name,
    PPCContext& ctx,
    std::uint8_t* base);

extern "C" RexPPCFunc daytona_resolve_import(
    const char* imp_name,
    const char* plain_name,
    const char* underscored_name);

#define DAYTONA_IMPORT_WRAPPER(name)                                      \
  extern "C" void daytona_##name(PPCContext& ctx, std::uint8_t* base) {   \
    static RexPPCFunc fn =                                                \
        daytona_resolve_import("__imp__" #name, #name, "_" #name);        \
    if (fn) {                                                             \
      fn(ctx, base);                                                      \
    } else {                                                             \
      ctx.r3.u64 = 0;                                                     \
    }                                                                    \
  }

DAYTONA_IMPORT_WRAPPER(DbgBreakPoint)
DAYTONA_IMPORT_WRAPPER(DbgPrint)
DAYTONA_IMPORT_WRAPPER(ExAllocatePoolTypeWithTag)
DAYTONA_IMPORT_WRAPPER(ExCreateThread)
DAYTONA_IMPORT_WRAPPER(ExFreePool)
DAYTONA_IMPORT_WRAPPER(ExGetXConfigSetting)
DAYTONA_IMPORT_WRAPPER(ExRegisterTitleTerminateNotification)
DAYTONA_IMPORT_WRAPPER(ExTerminateThread)
DAYTONA_IMPORT_WRAPPER(FscSetCacheElementCount)
DAYTONA_IMPORT_WRAPPER(HalReturnToFirmware)
DAYTONA_IMPORT_WRAPPER(IoCheckShareAccess)
DAYTONA_IMPORT_WRAPPER(IoCompleteRequest)
DAYTONA_IMPORT_WRAPPER(IoCreateDevice)
DAYTONA_IMPORT_WRAPPER(IoDeleteDevice)
DAYTONA_IMPORT_WRAPPER(IoInvalidDeviceRequest)
DAYTONA_IMPORT_WRAPPER(IoRemoveShareAccess)
DAYTONA_IMPORT_WRAPPER(IoSetShareAccess)
DAYTONA_IMPORT_WRAPPER(KeAcquireSpinLockAtRaisedIrql)
DAYTONA_IMPORT_WRAPPER(KeBugCheck)
DAYTONA_IMPORT_WRAPPER(KeBugCheckEx)
DAYTONA_IMPORT_WRAPPER(KeDelayExecutionThread)
DAYTONA_IMPORT_WRAPPER(KeEnableFpuExceptions)
DAYTONA_IMPORT_WRAPPER(KeEnterCriticalRegion)
DAYTONA_IMPORT_WRAPPER(KeGetCurrentProcessType)
DAYTONA_IMPORT_WRAPPER(KeInitializeDpc)
DAYTONA_IMPORT_WRAPPER(KeInsertQueueDpc)
DAYTONA_IMPORT_WRAPPER(KeLeaveCriticalRegion)
DAYTONA_IMPORT_WRAPPER(KeLockL2)
DAYTONA_IMPORT_WRAPPER(KeQueryBasePriorityThread)
DAYTONA_IMPORT_WRAPPER(KeQueryPerformanceFrequency)
DAYTONA_IMPORT_WRAPPER(KeQuerySystemTime)
DAYTONA_IMPORT_WRAPPER(KeReleaseSpinLockFromRaisedIrql)
DAYTONA_IMPORT_WRAPPER(KeResetEvent)
DAYTONA_IMPORT_WRAPPER(KeSetAffinityThread)
DAYTONA_IMPORT_WRAPPER(KeSetBasePriorityThread)
DAYTONA_IMPORT_WRAPPER(KeSetCurrentProcessType)
DAYTONA_IMPORT_WRAPPER(KeSetEvent)
DAYTONA_IMPORT_WRAPPER(KeTlsAlloc)
DAYTONA_IMPORT_WRAPPER(KeTlsFree)
DAYTONA_IMPORT_WRAPPER(KeTlsGetValue)
DAYTONA_IMPORT_WRAPPER(KeTlsSetValue)
DAYTONA_IMPORT_WRAPPER(KeUnlockL2)
DAYTONA_IMPORT_WRAPPER(KeWaitForMultipleObjects)
DAYTONA_IMPORT_WRAPPER(KeWaitForSingleObject)
DAYTONA_IMPORT_WRAPPER(KfAcquireSpinLock)
DAYTONA_IMPORT_WRAPPER(KfReleaseSpinLock)
DAYTONA_IMPORT_WRAPPER(KiApcNormalRoutineNop)
DAYTONA_IMPORT_WRAPPER(MmAllocatePhysicalMemoryEx)
DAYTONA_IMPORT_WRAPPER(MmFreePhysicalMemory)
DAYTONA_IMPORT_WRAPPER(MmGetPhysicalAddress)
DAYTONA_IMPORT_WRAPPER(MmLockAndMapSegmentArray)
DAYTONA_IMPORT_WRAPPER(MmMapIoSpace)
DAYTONA_IMPORT_WRAPPER(MmQueryAddressProtect)
DAYTONA_IMPORT_WRAPPER(MmUnlockAndUnmapSegmentArray)
DAYTONA_IMPORT_WRAPPER(NetDll_WSACleanup)
DAYTONA_IMPORT_WRAPPER(NetDll_WSAGetLastError)
DAYTONA_IMPORT_WRAPPER(NetDll_WSAGetOverlappedResult)
DAYTONA_IMPORT_WRAPPER(NetDll_WSARecvFrom)
DAYTONA_IMPORT_WRAPPER(NetDll_WSASendTo)
DAYTONA_IMPORT_WRAPPER(NetDll_WSAStartup)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetCleanup)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetConnect)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetGetConnectStatus)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetGetTitleXnAddr)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetQosListen)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetQosLookup)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetQosRelease)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetQosServiceLookup)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetRandom)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetStartup)
DAYTONA_IMPORT_WRAPPER(NetDll_XNetXnAddrToInAddr)
DAYTONA_IMPORT_WRAPPER(NetDll_bind)
DAYTONA_IMPORT_WRAPPER(NetDll_closesocket)
DAYTONA_IMPORT_WRAPPER(NetDll_ioctlsocket)
DAYTONA_IMPORT_WRAPPER(NetDll_recvfrom)
DAYTONA_IMPORT_WRAPPER(NetDll_sendto)
DAYTONA_IMPORT_WRAPPER(NetDll_setsockopt)
DAYTONA_IMPORT_WRAPPER(NetDll_socket)
DAYTONA_IMPORT_WRAPPER(NtAllocateVirtualMemory)
DAYTONA_IMPORT_WRAPPER(NtCancelTimer)
DAYTONA_IMPORT_WRAPPER(NtClearEvent)
DAYTONA_IMPORT_WRAPPER(NtClose)
DAYTONA_IMPORT_WRAPPER(NtCreateEvent)
DAYTONA_IMPORT_WRAPPER(NtCreateFile)
DAYTONA_IMPORT_WRAPPER(NtCreateMutant)
DAYTONA_IMPORT_WRAPPER(NtCreateSemaphore)
DAYTONA_IMPORT_WRAPPER(NtCreateTimer)
DAYTONA_IMPORT_WRAPPER(NtDuplicateObject)
DAYTONA_IMPORT_WRAPPER(NtFlushBuffersFile)
DAYTONA_IMPORT_WRAPPER(NtFreeVirtualMemory)
DAYTONA_IMPORT_WRAPPER(NtOpenFile)
DAYTONA_IMPORT_WRAPPER(NtQueryFullAttributesFile)
DAYTONA_IMPORT_WRAPPER(NtQueryDirectoryFile)
DAYTONA_IMPORT_WRAPPER(NtQueryInformationFile)
DAYTONA_IMPORT_WRAPPER(NtQueryVirtualMemory)
DAYTONA_IMPORT_WRAPPER(NtQueryVolumeInformationFile)
DAYTONA_IMPORT_WRAPPER(NtQueueApcThread)
DAYTONA_IMPORT_WRAPPER(NtReadFile)
DAYTONA_IMPORT_WRAPPER(NtReadFileScatter)
DAYTONA_IMPORT_WRAPPER(NtReleaseMutant)
DAYTONA_IMPORT_WRAPPER(NtReleaseSemaphore)
DAYTONA_IMPORT_WRAPPER(NtResumeThread)
DAYTONA_IMPORT_WRAPPER(NtSetEvent)
DAYTONA_IMPORT_WRAPPER(NtSetInformationFile)
DAYTONA_IMPORT_WRAPPER(NtSetTimerEx)
DAYTONA_IMPORT_WRAPPER(NtSuspendThread)
DAYTONA_IMPORT_WRAPPER(NtWaitForSingleObjectEx)
DAYTONA_IMPORT_WRAPPER(NtWriteFile)
DAYTONA_IMPORT_WRAPPER(NtWriteFileGather)
DAYTONA_IMPORT_WRAPPER(ObCreateSymbolicLink)
DAYTONA_IMPORT_WRAPPER(ObDeleteSymbolicLink)
DAYTONA_IMPORT_WRAPPER(ObDereferenceObject)
DAYTONA_IMPORT_WRAPPER(ObIsTitleObject)
DAYTONA_IMPORT_WRAPPER(ObReferenceObject)
DAYTONA_IMPORT_WRAPPER(ObReferenceObjectByHandle)
DAYTONA_IMPORT_WRAPPER(RtlCaptureContext)
DAYTONA_IMPORT_WRAPPER(RtlCompareMemoryUlong)
DAYTONA_IMPORT_WRAPPER(RtlCompareStringN)
DAYTONA_IMPORT_WRAPPER(RtlEnterCriticalSection)
DAYTONA_IMPORT_WRAPPER(RtlFillMemoryUlong)
DAYTONA_IMPORT_WRAPPER(RtlFreeAnsiString)
DAYTONA_IMPORT_WRAPPER(RtlImageXexHeaderField)
DAYTONA_IMPORT_WRAPPER(RtlInitAnsiString)
DAYTONA_IMPORT_WRAPPER(RtlInitUnicodeString)
DAYTONA_IMPORT_WRAPPER(RtlInitializeCriticalSection)
DAYTONA_IMPORT_WRAPPER(RtlInitializeCriticalSectionAndSpinCount)
DAYTONA_IMPORT_WRAPPER(RtlLeaveCriticalSection)
DAYTONA_IMPORT_WRAPPER(RtlMultiByteToUnicodeN)
DAYTONA_IMPORT_WRAPPER(RtlNtStatusToDosError)
DAYTONA_IMPORT_WRAPPER(RtlRaiseException)
DAYTONA_IMPORT_WRAPPER(RtlTimeFieldsToTime)
DAYTONA_IMPORT_WRAPPER(RtlTimeToTimeFields)
DAYTONA_IMPORT_WRAPPER(RtlTryEnterCriticalSection)
DAYTONA_IMPORT_WRAPPER(RtlUnicodeStringToAnsiString)
DAYTONA_IMPORT_WRAPPER(RtlUnicodeToMultiByteN)
DAYTONA_IMPORT_WRAPPER(RtlUnwind)
DAYTONA_IMPORT_WRAPPER(RtlUpcaseUnicodeChar)
DAYTONA_IMPORT_WRAPPER(StfsControlDevice)
DAYTONA_IMPORT_WRAPPER(StfsCreateDevice)
DAYTONA_IMPORT_WRAPPER(VdCallGraphicsNotificationRoutines)
DAYTONA_IMPORT_WRAPPER(VdEnableDisableClockGating)
DAYTONA_IMPORT_WRAPPER(VdEnableRingBufferRPtrWriteBack)
DAYTONA_IMPORT_WRAPPER(VdGetCurrentDisplayGamma)
DAYTONA_IMPORT_WRAPPER(VdGetCurrentDisplayInformation)
DAYTONA_IMPORT_WRAPPER(VdGetSystemCommandBuffer)
DAYTONA_IMPORT_WRAPPER(VdInitializeEngines)
DAYTONA_IMPORT_WRAPPER(VdInitializeRingBuffer)
DAYTONA_IMPORT_WRAPPER(VdInitializeScalerCommandBuffer)
DAYTONA_IMPORT_WRAPPER(VdIsHSIOTrainingSucceeded)
DAYTONA_IMPORT_WRAPPER(VdPersistDisplay)
DAYTONA_IMPORT_WRAPPER(VdQueryVideoFlags)
DAYTONA_IMPORT_WRAPPER(VdQueryVideoMode)
DAYTONA_IMPORT_WRAPPER(VdRetrainEDRAM)
DAYTONA_IMPORT_WRAPPER(VdRetrainEDRAMWorker)
DAYTONA_IMPORT_WRAPPER(VdSetDisplayMode)
DAYTONA_IMPORT_WRAPPER(VdSetDisplayModeOverride)
DAYTONA_IMPORT_WRAPPER(VdSetGraphicsInterruptCallback)
DAYTONA_IMPORT_WRAPPER(VdSetSystemCommandBufferGpuIdentifierAddress)
DAYTONA_IMPORT_WRAPPER(VdShutdownEngines)
DAYTONA_IMPORT_WRAPPER(VdSwap)
DAYTONA_IMPORT_WRAPPER(XAudioGetDuckerLevel)
DAYTONA_IMPORT_WRAPPER(XAudioGetSpeakerConfig)
DAYTONA_IMPORT_WRAPPER(XAudioGetVoiceCategoryVolume)
DAYTONA_IMPORT_WRAPPER(XAudioRegisterRenderDriverClient)
DAYTONA_IMPORT_WRAPPER(XAudioSubmitRenderDriverFrame)
DAYTONA_IMPORT_WRAPPER(XAudioUnregisterRenderDriverClient)
DAYTONA_IMPORT_WRAPPER(XGetAVPack)
DAYTONA_IMPORT_WRAPPER(XGetGameRegion)
DAYTONA_IMPORT_WRAPPER(XGetLanguage)
DAYTONA_IMPORT_WRAPPER(XGetVideoMode)
DAYTONA_IMPORT_WRAPPER(XMACreateContext)
DAYTONA_IMPORT_WRAPPER(XMAReleaseContext)
DAYTONA_IMPORT_WRAPPER(XMsgCancelIORequest)
DAYTONA_IMPORT_WRAPPER(XMsgInProcessCall)
DAYTONA_IMPORT_WRAPPER(XMsgStartIORequest)
DAYTONA_IMPORT_WRAPPER(XNetLogonGetTitleID)
DAYTONA_IMPORT_WRAPPER(XNotifyGetNext)
DAYTONA_IMPORT_WRAPPER(XNotifyPositionUI)
DAYTONA_IMPORT_WRAPPER(XamAlloc)
DAYTONA_IMPORT_WRAPPER(XamContentClose)
DAYTONA_IMPORT_WRAPPER(XamContentCreateEnumerator)
DAYTONA_IMPORT_WRAPPER(XamContentCreateEx)
DAYTONA_IMPORT_WRAPPER(XamContentGetCreator)
DAYTONA_IMPORT_WRAPPER(XamContentGetDeviceData)
DAYTONA_IMPORT_WRAPPER(XamContentGetDeviceState)
extern "C" void __imp__XamContentGetLicenseMask(PPCContext& ctx, std::uint8_t* base);
extern "C" void daytona_XamContentGetLicenseMask(PPCContext& ctx, std::uint8_t* base) {
  __imp__XamContentGetLicenseMask(ctx, base);
}
DAYTONA_IMPORT_WRAPPER(XamContentSetThumbnail)
DAYTONA_IMPORT_WRAPPER(XamEnumerate)
DAYTONA_IMPORT_WRAPPER(XamFree)
DAYTONA_IMPORT_WRAPPER(XamGetExecutionId)
DAYTONA_IMPORT_WRAPPER(XamGetSystemVersion)
DAYTONA_IMPORT_WRAPPER(XamInputGetCapabilities)
DAYTONA_IMPORT_WRAPPER(XamInputGetCapabilitiesEx)
DAYTONA_IMPORT_WRAPPER(XamInputGetState)
DAYTONA_IMPORT_WRAPPER(XamInputRawState)
DAYTONA_IMPORT_WRAPPER(XamInputSetState)
DAYTONA_IMPORT_WRAPPER(XamLoaderLaunchTitle)
DAYTONA_IMPORT_WRAPPER(XamLoaderTerminateTitle)
DAYTONA_IMPORT_WRAPPER(XamNotifyCreateListener)
DAYTONA_IMPORT_WRAPPER(XamSessionCreateHandle)
DAYTONA_IMPORT_WRAPPER(XamSessionRefObjByHandle)
DAYTONA_IMPORT_WRAPPER(XamShowAchievementsUI)
DAYTONA_IMPORT_WRAPPER(XamShowDeviceSelectorUI)
DAYTONA_IMPORT_WRAPPER(XamShowDirtyDiscErrorUI)
DAYTONA_IMPORT_WRAPPER(XamShowFriendsUI)
DAYTONA_IMPORT_WRAPPER(XamShowGameInviteUI)
DAYTONA_IMPORT_WRAPPER(XamShowGamerCardUIForXUID)
DAYTONA_IMPORT_WRAPPER(XamShowKeyboardUI)
DAYTONA_IMPORT_WRAPPER(XamShowMarketplaceUI)
DAYTONA_IMPORT_WRAPPER(XamShowMessageBoxUI)
DAYTONA_IMPORT_WRAPPER(XamShowMessageBoxUIEx)
DAYTONA_IMPORT_WRAPPER(XamShowPlayerReviewUI)
DAYTONA_IMPORT_WRAPPER(XamShowQuickChatUI)
DAYTONA_IMPORT_WRAPPER(XamShowSigninUI)
DAYTONA_IMPORT_WRAPPER(XamUserAreUsersFriends)
DAYTONA_IMPORT_WRAPPER(XamUserCheckPrivilege)
DAYTONA_IMPORT_WRAPPER(XamUserCreateStatsEnumerator)
DAYTONA_IMPORT_WRAPPER(XamUserGetDeviceContext)
DAYTONA_IMPORT_WRAPPER(XamUserGetName)
DAYTONA_IMPORT_WRAPPER(XamUserGetSigninInfo)
DAYTONA_IMPORT_WRAPPER(XamUserGetSigninState)
DAYTONA_IMPORT_WRAPPER(XamUserGetXUID)
DAYTONA_IMPORT_WRAPPER(XamUserReadProfileSettings)
DAYTONA_IMPORT_WRAPPER(XamVoiceClose)
DAYTONA_IMPORT_WRAPPER(XamVoiceCreate)
DAYTONA_IMPORT_WRAPPER(XamVoiceHeadsetPresent)
DAYTONA_IMPORT_WRAPPER(XamVoiceIsActiveProcess)
DAYTONA_IMPORT_WRAPPER(XamVoiceSubmitPacket)
DAYTONA_IMPORT_WRAPPER(XamWriteGamerTile)
DAYTONA_IMPORT_WRAPPER(XeCryptSha)
DAYTONA_IMPORT_WRAPPER(XexCheckExecutablePrivilege)
DAYTONA_IMPORT_WRAPPER(XexGetModuleHandle)
DAYTONA_IMPORT_WRAPPER(XexGetModuleSection)
DAYTONA_IMPORT_WRAPPER(XexGetProcedureAddress)
DAYTONA_IMPORT_WRAPPER(XexLoadImage)
DAYTONA_IMPORT_WRAPPER(XexUnloadImage)
DAYTONA_IMPORT_WRAPPER(__C_specific_handler)
DAYTONA_IMPORT_WRAPPER(_snprintf)
DAYTONA_IMPORT_WRAPPER(_vsnprintf)
DAYTONA_IMPORT_WRAPPER(sprintf)

#undef DAYTONA_IMPORT_WRAPPER
